// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0Y21cisiEDVFJ1RCgcLXF7L3D7wJTWE',
    appId: '1:726273838977:android:977832f348cc11accde280',
    messagingSenderId: '726273838977',
    projectId: 'projeapp-fb313',
    storageBucket: 'projeapp-fb313.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOMuqAC09M8yxWWMH5XnjcBIrCkxBWmrM',
    appId: '1:726273838977:ios:1a02eedbc8b5a5cecde280',
    messagingSenderId: '726273838977',
    projectId: 'projeapp-fb313',
    storageBucket: 'projeapp-fb313.firebasestorage.app',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwm8KMyyr-IUEDAFjiYoscB0brM4O2v6c',
    appId: '1:726273838977:web:9a61b75256c351c0cde280',
    messagingSenderId: '726273838977',
    projectId: 'projeapp-fb313',
    authDomain: 'projeapp-fb313.firebaseapp.com',
    storageBucket: 'projeapp-fb313.firebasestorage.app',
    measurementId: 'G-YXGYB79M1R',
  );

}